### ISSUE TITLE
Suggestion: Update the 2D Primitives link with the project here on GitHub

### ISSUE THREAD

**Issue by DoogeJ** [aloisdeniel/awesome-monogame#24]
Hi!

Awesome/impressive list and very helpful!

I did notice the 2D Primitives project on there (the one that extends `spritebatch`).
Made a post to let you know that some years ago I've updated that project to use MonoGame and since a few days there is also a NuGet Package:

https://github.com/DoogeJ/MonoGame.Primitives2D

Examples: https://github.com/DoogeJ/MonoGame.Primitives2D.Sample

NuGet: https://www.nuget.org/packages/MonoGame.Primitives2D/

**Comment by aloisdeniel** [comment]
Thanks, I updated the link and added the stars badge.
